name: Auto update host machine

on:
  push:
    branches:
      - master
      - dev-three
jobs:
  pull-new-version:
    runs-on: self-hosted

    steps:
      - name: pull code
        run: |
          cd ~/WarehouseWebsite
          git pull WarehouseWebsite master
          git pull WarehouseWebsite dev-three
